# Generated by Django 4.0.4 on 2022-08-05 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 5, 14, 55, 2, 976812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='at_location',
            field=models.TimeField(default=datetime.datetime(2022, 8, 5, 14, 55, 2, 992439, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start_time', models.TimeField()),
                ('reservation_end_time', models.TimeField()),
                ('personality', models.CharField(max_length=80)),
                ('seats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seating')),
            ],
        ),
    ]
