# Generated by Django 4.0.4 on 2022-08-10 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_start_time_alter_timetable_at_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 10, 17, 27, 23, 829865, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='at_location',
            field=models.TimeField(default=datetime.datetime(2022, 8, 10, 17, 27, 23, 829865, tzinfo=utc)),
        ),
    ]
